# numpy基础

numpy的基础知识:
1. numpy在数组操作上的效率是优于纯python代码

In [2]:
import numpy as np

array1 = np.arange(0, 10, 2)

print(array1)
print(type(array1))

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [4]:
import numpy as np

def sum(n):
    """两个数组的求和"""
    a = np.arange(n) ** 2
    b = np.arange(n) ** 3
    c = a + b
    return c

result = sum(10)
print(result)

[  0   2  12  36  80 150 252 392 576 810]


In [3]:
import numpy as np

In [4]:
a = np.arange(5)

In [12]:
a.dtype

dtype('int32')

### 创建多维数组

In [13]:
a = np.array([np.arange(4), np.arange(4)])

In [16]:
a

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

### 查看数组的维数
shape属性

In [17]:
a.shape

(2, 4)

### 选取多维数组中的数据

In [18]:
a[0, 2]

2

### numpy常用数据类型
1. bool
2. inti, 所在平台决定精度
3. float32, 单精度浮点数
4. complex64, 复数,用两个32位浮点数表示实部和虚部

### 一维数组的索引和切片

In [19]:
a = np.arange(9)
a[3:7]

array([3, 4, 5, 6])

In [20]:
a[:7:2]

array([0, 2, 4, 6])

In [21]:
a[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

### 多维数组的索引和切片
reshape()函数改变数组的纬度

In [23]:
# arange创建一个数组并改变其纬度为三维数组
b = np.arange(24).reshape(2, 3, 4)  # 生成的是一个2*3*4的三维数组
b.shape

(2, 3, 4)

In [24]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

### 数组的组合

In [27]:
# 生成一个3*3的二维数组
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
# 产生另一个数组
b = 2 * a
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

#### 数组水平拼接
hstack()函数
或者concatenate((a,b),axis=1)函数

In [33]:
np.hstack((a, b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

#### 数组垂直组合
vstack()函数
或concatenate((a,b),axis=0)

In [34]:
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

#### 数组深度组合
1. 前提是两个数组行列数均相同
2. 含义为将一系列数组沿着纵轴(深度)方向进行重叠组合,一维变二维,二维变三维
3. 使用dstack()函数

In [35]:
np.dstack((a, b))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

#### 数组分割
1. 水平分割, hsplit()
2. 垂直分割, vsplit()
3. 深度分割, dsplit()

In [37]:
c = np.arange(27).reshape(3,3,3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [45]:
for i in np.hsplit(a,3):
    print("array:", i)
    print("\n")

array: [[0]
 [3]
 [6]]


array: [[1]
 [4]
 [7]]


array: [[2]
 [5]
 [8]]




In [46]:
for i in np.vsplit(a,3):
    print("array:", i)
    print("\n")

array: [[0 1 2]]


array: [[3 4 5]]


array: [[6 7 8]]




In [50]:
for i in np.hsplit(c,3):
    print("array:", i)
    print("\n")

array: [[[ 0  1  2]]

 [[ 9 10 11]]

 [[18 19 20]]]


array: [[[ 3  4  5]]

 [[12 13 14]]

 [[21 22 23]]]


array: [[[ 6  7  8]]

 [[15 16 17]]

 [[24 25 26]]]




### 数组的属性
1. ndim,数组的维数
2. size,数组元素的总个数
3. itemsize,数组中元素在内存中所占的字节数
4. nbytes,整个数组所占存储空间

In [52]:
c.ndim

3

In [53]:
c.size

27

In [54]:
c.itemsize

4

In [55]:
c.nbytes

108

#### 数组转换为python列表
tolist()函数

In [6]:
import numpy as np
a = np.arange(12).reshape(3, 4)
b = a.tolist()
print(type(b))
print(b)

<class 'list'>
[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]
