# numpy常用函数

### 创建一个单位矩阵并将其存储到文件中
eye()函数创建单位矩阵

In [2]:
import numpy as np
i4 = np.eye(4)
i4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### 将数据存储到文件中
savetxt()函数

In [3]:
np.savetxt("./eye.txt", i4)

### 读入csv文件中的数据
1. 数据库的转存文件就是csv格式
2. loadtxt()函数

In [6]:
# 读取股票中的收盘价以及成交量,分隔符为,
c, v = np.loadtxt("./data.csv", delimiter=",", usecols=(6, 7), unpack=True)
# 计算成交量加权平均价格
vwap =  np.average(c, weights=v)

print("c: ", c)
print("v:", v)
print("vwap:", vwap)

c:  336.1
v: 21144800.0
vwap: 336.1


#### 简单的统计分析

In [3]:
import numpy as np
# 读取文件中的数据
c = np.loadtxt("./data.csv", delimiter=",", usecols=(3, 4, 5, 6), unpack=True)
print("c: ", type(c), c)

# 中位数
medi = np.median(c)
print("中位数: ", medi)

# 算术平均数
ave = np.mean(c)
print("算术平均数: ", ave)

# 最大值
max_num = np.max(c)
print("最大值: ", max_num)

# 最小值
min_num = np.min(c)
print("最小值: ", min_num)

# 方差
variance = np.var(c)
print("方差: ", variance)

# 最大元素的索引
s1 = np.argmax(c)
print("最大元素的索引: ", s1)

# 最小元素的索引
s2 = np.argmin(c)
print("最小元素的索引: ", s2)

# 所有元素的累积和(每个元素累加自己之前的所有元素)
sum_all = np.cumsum(c)
print("所有元素之和: ", sum_all)

# 所有元素的累计积(每个元素累乘自己之前的所有元素)
result1 = np.cumprod(c)
print("所有元素之积: ", result1)

c:  <class 'numpy.ndarray'> [344.17 344.4  333.53 336.1 ]
中位数:  340.135
算术平均数:  339.54999999999995
最大值:  344.4
最小值:  333.53
方差:  23.252450000000028
最大元素的索引:  1
最小元素的索引:  2
所有元素之和:  [ 344.17  688.57 1022.1  1358.2 ]
所有元素之积:  [3.44170000e+02 1.18532148e+05 3.95340273e+07 1.32873866e+10]


#### 简单数组排序

In [5]:
c.sort()
c

array([333.53, 336.1 , 344.17, 344.4 ])

### 线性代数

numpy.linalg中的一组函数:
1. dot()用于矩阵乘法
2. det()计算矩阵的行列式
3. eig()计算方阵的本征值和本征向量
4. inv()计算方阵的逆
5. solve()解线性方程组Ax=b,其中A为方阵
6. svd()计算奇异值分解(SVD)

In [7]:
import numpy as np

a = np.arange(6).reshape(2, 3)
b = np.arange(6).reshape(3, 2)
c = np.dot(a, b)
print("a:\n", a)
print("b:\n", b)

print("c:\n", c)

a:
 [[0 1 2]
 [3 4 5]]
b:
 [[0 1]
 [2 3]
 [4 5]]
c:
 [[10 13]
 [28 40]]


In [11]:
from numpy.linalg import *
# 行列式
det(c)

36.0

In [13]:
# 方阵的本征值和本征向量
result = eig(c)
for item in result:
    print(item)
    print("\n")

[ 0.7306778 49.2693222]


[[-0.81421878 -0.31427384]
 [ 0.58055817 -0.94933237]]





#### 随机数生成
numpy.random模块
1. rand()产生均匀分布的样本值
2. randint()从给定的上下限范围内随机选取整数
3. randn()产生正态分布(均值为0,标准差为1)的样本值
4. binomial()产生二项分布的样本值
5. normal()产生正态(高斯)分布的样本值


6. beta()产生Beta分布的样本值
7. chisquare()产生卡方分布的样本值
8. gamma()产生Gamma分布的样本值


9. uniform()产生在[0,1]中均匀分布的样本值

In [14]:
from numpy.random import *

# 利用normal()得到一个标准正态分布的4*4样本数组
samples = normal(size=(4, 4))
samples

array([[ 0.51341641, -0.63023488, -1.05918974,  1.41368505],
       [ 0.69850955,  0.01534258, -3.31591792, -3.01610039],
       [-0.54145364,  0.63134406, -0.74711948,  0.04875474],
       [ 0.81699702,  0.796563  ,  0.26422571, -1.4474639 ]])

In [25]:
rand(2, 2)

array([[0.91238036, 0.18128263],
       [0.7135678 , 0.59519867]])

In [57]:
a = randint(10)
print("a:", a)

b = randint(low=10, high=20, size=(2,3))
print("b:", b)

a: 1
b: [[13 13 17]
 [12 16 19]]


In [212]:
# 前一个位置参数表示范围,后一个表示概率,最后一个表示个数
a = binomial(2, 1)
print(a)

b = binomial(3, 0.5, 20)
print(b)

c = binomial(1, 0.5, 100)
print(c)
possiablity = sum(c==0)/100
print(possiablity)

2
[1 2 2 1 1 1 1 1 2 2 0 1 0 1 2 2 2 3 2 1]
[1 0 0 0 0 1 1 1 1 0 1 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 1 0 1 1 1 1 1 1 0 1 1
 1 1 1 0 1 0 0 0 0 0 1 0 1 0 0 0 1 1 1 1 1 1 0 1 0 0 1 0 0 0 1 1 1 1 0 0 1
 0 1 1 1 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 1 1]
0.39
